# manifests/delivery-simulator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-simulator
  namespace: planet-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-simulator
  template:
    metadata:
      labels:
        app: delivery-simulator
    spec:
      containers:
        - name: delivery-simulator
          image: wilgrimthepilgrim/traffic:latest
          env:
            - name: API_URL
              value: "http://planetexpress-api/deliveries"
            - name: INTERVAL_SECONDS
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: planetexpress-traffic
  namespace: planet-express
  labels:
    app: planetexpress-traffic
spec:
  selector:
    app: planetexpress-traffic
  ports:
    - port: 2112
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: planetexpress-traffic
  namespace: planet-express
spec:
  selector:
    matchLabels:
      app: planetexpress-traffic
  endpoints:
    - port: metrics
