# manifests/delivery-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planetexpress-delivery
  namespace: planet-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planetexpress-delivery
  template:
    metadata:
      labels:
        app: planetexpress-delivery
    spec:
      containers:
        - name: planetexpress-delivery
          image: wilgrimthepilgrim/delivery:latest
          env:
            - name: CREW_SERVICE_URL
              value: "http://crew-service"
            - name: SHIP_SERVICE_URL
              value: "http://ship-service"
            - name: PACKAGE_SERVICE_URL
              value: "http://package-service"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 2112
              name: metrics
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: planetexpress-delivery
  namespace: planet-express
spec:
  selector:
    app: planetexpress-delivery
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 2112
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: planetexpress-delivery
  namespace: planet-express
spec:
  selector:
    matchLabels:
      app: planetexpress-delivery
  endpoints:
    - port: metrics
