# manifests/planetexpress-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planetexpress-api
  namespace: planet-express
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planetexpress-api
  template:
    metadata:
      labels:
        app: planetexpress-api
    spec:
      containers:
        - name: planetexpress-api
          image: wilgrimthepilgrim/api:latest
          env:
            - name: DELIVERY_SERVICE_URL
              value: "http://delivery-service"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 2112
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: planetexpress-api
  namespace: planet-express
  labels:
    app: planetexpress-api
spec:
  selector:
    app: planetexpress-api
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 2112
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: planetexpress-api
  namespace: planet-express
spec:
  selector:
    matchLabels:
      app: planetexpress-api
  endpoints:
    - port: metrics
